### ISSUE TITLE
Figure out why second row (of images) isn't working in "project skynet" section

### ISSUE THREAD

**Issue by dubh-SKM** [dubh-SKM/cyberdyne-systems#18]

**Comment by cobyfielding** [comment]
I noticed a few things here.  Your image names are incorrect in your css lines 175 and 180.  I assume you changed the image you were using but left the word `box` in the name, so those images don't exist.  The second issue you have is that you are using a row but don't have any column classes.  I would prob add `col-sm-12` and `col-md-6` to both of those images.  The third issue you have is that columns don't have a default height and neither do div tags, so if you are using `background-image` instead of an image tag you have to assign a height to something in that row.  I would give both images a height of 400px then it should match the size of what's above it.  Here is what it looks like for me after making the above changes 
<img width="2271" alt="Screen Shot 2022-10-27 at 6 10 44 PM" src="https://user-images.githubusercontent.com/15643192/198430812-d94bb270-f978-4572-8524-214c6899d2ab.png">

**Comment by dubh-SKM** [comment]
That's it.  Thank you!
