### ISSUE TITLE
Fix image repeat on second carousel slide

### ISSUE THREAD

**Issue by dubh-SKM** [dubh-SKM/cyberdyne-systems#9]

**Comment by cobyfielding** [comment]
If you are referring to the broken image tag showing (see screenshot), it's because you don't have the image element commented out like you do on the other ones.  See line 99 on your Hero responsive branch https://github.com/dubh-SKM/cyberdyne-systems/blob/hero-responsive/index.html#L99
If you aren't referring to the broken image tag, then please clarify which branch you are seeing the image repeat
<img width="1615" alt="Screen Shot 2022-10-27 at 5 50 12 PM" src="https://user-images.githubusercontent.com/15643192/198424030-40599684-5ab1-4590-acda-8fff064864c2.png">

**Comment by dubh-SKM** [comment]
Ahh yes, that was it.  Thanks!
